services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: recovery-sqlserver
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=${MSSQL_SA_PASSWORD}
    ports:
      - "11433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
    networks:
      - recovery-network
    healthcheck:
        test: ["CMD-SHELL", "pgrep sqlservr || exit 1"]
        interval: 10s
        timeout: 5s
        retries: 10

  rabbitmq:
    image: rabbitmq:3.12-management
    container_name: recovery-rabbitmq
    ports:
      - "25672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - recovery-network
    healthcheck:
      test: [ "CMD", "rabbitmqctl", "status" ]
      interval: 10s
      timeout: 5s
      retries: 5

  identity-service:
    build:
      context: .
      dockerfile: src/Services/IdentityService/RecoverySystem.IdentityService/Dockerfile
    container_name: recovery-identity-service
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__DefaultConnection=${IDENTITY_DB}
      - Jwt__Key=YourSuperSecretKey12345678901234567890
      - Jwt__Issuer=RecoverySystem
      - Jwt__Audience=RecoverySystemClients
      - Jwt__ExpireDays=30
      - RabbitMQ__HostName=rabbitmq
      - RabbitMQ__UserName=guest
      - RabbitMQ__Password=guest
    ports:
      - "5001:5001"
    networks:
      - recovery-network
    depends_on:
      sqlserver:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    restart: on-failure

  patient-service:
    build:
      context: .
      dockerfile: src/Services/PatientService/RecoverySystem.PatientService/Dockerfile
    container_name: recovery-patient-service
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__DefaultConnection=${PATIENT_DB}
      - Jwt__Key=YourSuperSecretKey12345678901234567890
      - Jwt__Issuer=RecoverySystem
      - Jwt__Audience=RecoverySystemClients
      - Jwt__ExpireDays=30
      - RabbitMQ__HostName=rabbitmq
      - RabbitMQ__UserName=guest
      - RabbitMQ__Password=guest
    ports:
      - "5002:5002"
    networks:
      - recovery-network
    depends_on:
      sqlserver:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      identity-service:
        condition: service_started
    restart: on-failure

  case-service:
    build:
      context: .
      dockerfile: src/Services/CaseService/RecoverySystem.CaseService/Dockerfile
    container_name: recovery-case-service
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__DefaultConnection=${CASE_DB}
      - Jwt__Key=YourSuperSecretKey12345678901234567890
      - Jwt__Issuer=RecoverySystem
      - Jwt__Audience=RecoverySystemClients
      - Jwt__ExpireDays=30
      - RabbitMQ__HostName=rabbitmq
      - RabbitMQ__UserName=guest
      - RabbitMQ__Password=guest
    ports:
      - "5003:5003"
    networks:
      - recovery-network
    depends_on:
      sqlserver:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      identity-service:
        condition: service_started
    restart: on-failure

  monitoring-service:
    build:
      context: .
      dockerfile: src/Services/MonitoringService/RecoverySystem.MonitoringService/Dockerfile
    container_name: recovery-monitoring-service
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__DefaultConnection=${MONITORING_DB}
      - Jwt__Key=YourSuperSecretKey12345678901234567890
      - Jwt__Issuer=RecoverySystem
      - Jwt__Audience=RecoverySystemClients
      - Jwt__ExpireDays=30
      - RabbitMQ__HostName=rabbitmq
      - RabbitMQ__UserName=guest
      - RabbitMQ__Password=guest
    ports:
      - "5004:5004"
    networks:
      - recovery-network
    depends_on:
      sqlserver:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      identity-service:
        condition: service_started
    restart: on-failure

  # notification-service:
  #   build:
  #     context: .
  #     dockerfile: src/Services/NotificationService/RecoverySystem.NotificationService/Dockerfile
  #   container_name: recovery-notification-service
  #   environment:
  #     - ASPNETCORE_ENVIRONMENT=Development
  #     - ASPNETCORE_URLS=http://+:80
  #     - ConnectionStrings__DefaultConnection=${NOTIFICATION_DB}
  #     - Jwt__Key=YourSuperSecretKey12345678901234567890
  #     - Jwt__Issuer=RecoverySystem
  #     - Jwt__Audience=RecoverySystemClients
  #     - Jwt__ExpireDays=30
  #     - RabbitMQ__HostName=rabbitmq
  #     - RabbitMQ__UserName=guest
  #     - RabbitMQ__Password=guest
  #   ports:
  #     - "5005:5005"
  #   networks:
  #     - recovery-network
  #   depends_on:
  #     sqlserver:
  #       condition: service_healthy
  #     rabbitmq:
  #       condition: service_healthy
  #     identity-service:
  #       condition: service_started
  #   restart: on-failure

  rehabilitation-service:
    build:
      context: .
      dockerfile: src/Services/RehabilitationService/Dockerfile
    container_name: recovery-rehabilitation-service
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__DefaultConnection=${REHABILITATION_DB}
      - Jwt__Key=YourSuperSecretKey12345678901234567890
      - Jwt__Issuer=RecoverySystem
      - Jwt__Audience=RecoverySystemClients
      - Jwt__ExpireDays=30
      - RabbitMQ__HostName=rabbitmq
      - RabbitMQ__UserName=guest
      - RabbitMQ__Password=guest
    ports:
      - "5006:5006"
    networks:
      - recovery-network
    depends_on:
      sqlserver:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      identity-service:
        condition: service_started
    restart: on-failure

  recommendation-service:
    build:
      context: .
      dockerfile: src/Services/RecommendationService/Dockerfile
    container_name: recovery-recommendation-service
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__DefaultConnection=${RECOMMENDATION_DB}
      - Jwt__Key=YourSuperSecretKey12345678901234567890
      - Jwt__Issuer=RecoverySystem
      - Jwt__Audience=RecoverySystemClients
      - Jwt__ExpireDays=30
      - RabbitMQ__HostName=rabbitmq
      - RabbitMQ__UserName=guest
      - RabbitMQ__Password=guest
    ports:
      - "5007:5007"
    networks:
      - recovery-network
    depends_on:
      sqlserver:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      identity-service:
        condition: service_started
    restart: on-failure

networks:
  recovery-network:
    driver: bridge

volumes:
  sqlserver_data:
  rabbitmq_data:

